extends: default
rules:
  line-length:
    max: 120
    level: warning
  comments-indentation: disable
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
